
services:
  app:
    build: .
    container_name: website_pay
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - mysql
    volumes:
      - laravel_storage:/var/www/html/storage
      - laravel_cache:/var/www/html/bootstrap/cache

  mysql:
    image: mysql:8.0
    container_name: website_pay-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_FORWARD_PORT:-3307}:3306"

volumes:
  mysql_data:
  laravel_storage:
  laravel_cache: